export { HeroSection } from './HeroSection'
export { VSLSection } from './VSLSection'
export { HeroVSLScroll } from './HeroVSLScroll'
export { ProblemSolutionSection } from './ProblemSolutionSection'
export { CurriculumSection } from './CurriculumSection'
export { AuthorSection } from './AuthorSection'
export { OfferSection } from './OfferSection'
